---
# tasks file for ansible_galaxy

- name: install apache2 on hosts machines
  apt:
    name: apache2
    state: present
    update_cache: yes      
- name: copy index file to destination
  copy:
    src: files/home.html
    dest: /var/www/html
    owner: root
    group: root
    mode: '0755'
                            
